### ISSUE TITLE
Implement PUT to change pothole data in the database

### ISSUE THREAD

**Issue by mhoc** [indy-pothole-tracker/project-management#10]

**Comment by michael-pr** [comment]
I tested this today, should be working..... Documentation:

http://localhost:8080/api/ReportPothole?api_key=123
POST request
Body:
{
   "latitude":12.2,
   "longitude":12.2
}

**Comment by michael-pr** [comment]
Wrong ticket ...

**Comment by michael-pr** [comment]
Update via latitude/longitude location

http://localhost:8080/api/ReportPothole?api_key=123
POST request
Body:
{
   "latitude":100.25233412,
   "longitude":78.251234123,
   "severity":10
}
