### ISSUE TITLE
Implement POST to create new potholes in database

### ISSUE THREAD

**Issue by mhoc** [indy-pothole-tracker/project-management#8]

**Comment by michael-pr** [comment]
I tested this today, should be working..... Documentation:

http://localhost:8080/api/ReportPothole?api_key=123
POST request
Body:
{
"latitude":12.2,
"longitude":12.2
}

**Comment by michael-pr** [comment]
Added severity:

{
   "latitude":100.25233412,
   "longitude":78.251234123,
   "severity":10
}
